---
# tasks file for pkg-install
- name: ensure nginx is at the latest version
  apt: name=nginx state=latest
  become: yes
- name: start nginx
  service:
      name: nginx
      state: started
  become: yes
- name: copy the nginx config file and restart nginx
  template:
    src: lb.cfg
    dest: /etc/nginx/sites-available/lb.conf
  become: yes
- name: create symlink
  file:
    src: /etc/nginx/sites-available/lb.conf
    dest: /etc/nginx/sites-enabled/lb.conf
    state: link
  become: yes
- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
