---

- name: Install Jenkins software

  hosts: node

  gather_facts: false

  pre_tasks:
  - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  become: yes

  become_method: sudo

  tags: [jenkins]

  tasks:

#    - name: Download jenkins repo

 #     shell: wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -

 #   - name: Import Jenkins CI key
  #    shell: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

    - name: Update the software package repository

      apt:

        update_cache: yes

        cache_valid_time: 86400 #One day

#    - name: Instal Java

   #   action: shell echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

    - name: Install dependencies

      apt: 

          name:

          - 'build-essential'

          - 'wget'

          - 'git'

          - 'default-jre'

          - 'default-jdk'

          - openjdk-8-jre

          - openjdk-8-jdk

    - name: install jenkins

      apt:

        name: jenkins

        update_cache: 

        state: present

    - name: Allow port 8080

      shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT

    - name: Start the server

      service:

          name: jenkins

          state: started

    - wait_for:

      port: 8080
